### ISSUE TITLE
Respons mini ex_5 by Sylvester Schelde Andersen

### ISSUE THREAD

**Issue by SylvesterSA** [nynnelucca/Mini-exercises#7]
First of all, really beautiful work. It's evident you've put a lot of emphasis on the aesthetic beauty from a visual and audio standpoint. It is a somewhat daunting, but yet still soothing piece, given the slow and drawn-out nature of both the musical piece and the clouds drifting by. 
By reading your readme file it's clear you have many thought behind this work, one of them being (as you mention) humanity living in real-time streams, where you include yourself as being online almost exclusively. I would like to know more about the data you initially would have like shown. What kind of data are you thinking? How would you show it? What effect does it have? 
You say that your work doesn't have a ton of relation to either the rita library or electronic litteratur in general, but i was wondering if maybe it's possible to still speak of the materiality of your work? 
You mention materiality a lot at the end of our readme, and finish with: " it must be recognized that electronic literature have a lot of different opportunities than an ordinary book."
So my question is: What opportunities does "Standing-Reserve" have that could perhaps show materiality? 

My immediate thoughts are these (and perhaps you agree): 
- The emotional bond you attempt to create between your work and the user (via use of imagery, music, general tone of mood etc) may be a part of materiality (even though there isn't interaction, i still consider it a viable thought). 
- What would the effects be if i (as a user) where to manipulate the source text? This is a definite difference between old and new media. 

All things said, really great program. Once you realize the reasoning behind the name, it really resonates (personally) with me.

**Comment by siusoon** [comment]
@SylvesterSA  excellent feedback where you have pushed the author to think deeper on the notion of materiality, and at the same time you are offering your own articulation.
